function exibirConselhos(tipo) {
   
    const container = document.getElementById('conselhos-container');
    const tabela = document.getElementById('tabela-conselhos');
    const titulo = document.getElementById('titulo-conselhos');
    const tbody = tabela.querySelector('tbody');

   
    const conselhos = {
        romantico: [
"Se você pudesse passar um mês em qualquer lugar do mundo, onde seria?",
"Qual é o maior sonho que você ainda não contou para ninguém?",
"Você já fez algo completamente louco ou impulsivo que acabou sendo incrível?",
"Qual foi a última vez que você ficou sem palavras por causa de algo que viu ou ouviu?",
"Se tivesse que escolher uma superpotência, qual escolheria?",
"Você tem alguma habilidade secreta que pouca gente sabe?",
"Qual foi a coisa mais espontânea que você já fez e adorou?",
"Qual é a sua maior filosofia de vida até agora?",
"Se pudesse aprender qualquer coisa nova, o que você escolheria?",
"Qual seria o seu rolê perfeito para um sábado à noite?",
"Se pudesse mudar uma coisa na sua rotina, o que mudaria?",
"Você é mais de sair para uma balada ou curtir um rolê tranquilo?",
"Tem algum lugar que você sempre quis visitar, mas ainda não teve oportunidade?",
"Qual foi o último livro ou série que você não conseguia parar de falar?",
"Qual é o maior erro de viagem que você já cometeu, mas que se tornou uma história épica?",
"Se você pudesse jantar com qualquer pessoa do mundo, quem seria?",
"Qual é o tipo de música que mais te define?",
"Você já fez algo totalmente fora da sua zona de conforto? Como foi?",
"Qual seria a primeira coisa que você faria se tivesse 1 milhão de reais agora?",
"Qual é o maior desafio que você já superou até agora e como isso te mudou?",
"Tem alguma coisa que você sempre quis fazer, mas nunca teve coragem?",
"Qual foi o melhor conselho que você já recebeu e aplicou na sua vida?",
"Qual seria o título da sua biografia até agora?",
"Você acredita que as coisas acontecem por acaso ou há sempre um propósito?",
"Qual seria o trabalho dos seus sonhos, sem preocupações com dinheiro?",
"Qual é o melhor tipo de dia para você? Cheio de aventuras ou mais tranquilo?",
"Você tem alguma memória de infância que te faz sorrir toda vez que lembra?",
"Qual foi a última vez que você se surpreendeu com algo pequeno, mas impactante?",
"Tem algum hobby que você adora, mas pouca gente entende?",
"Qual é o melhor jeito de relaxar para você após uma semana agitada?",
"Se você fosse escrever um livro sobre sua vida, qual seria o nome?",
"Você acredita mais no destino ou no poder das escolhas?",
"Qual foi o lugar mais inesperado onde você encontrou uma paz enorme?",
"Qual é o tipo de filme ou série que sempre te faz querer mais?",
"Se sua vida fosse uma playlist, quais seriam as músicas principais?",
"O que você acha que as pessoas geralmente não entendem sobre você?",
"Você tem alguma superstição ou crença pessoal que te guia?",
"Qual é a coisa mais aleatória que você gostaria de aprender a fazer?",
"Se tivesse um dia inteiro para se dedicar a um só hobby, qual escolheria?",
"Qual é o lugar onde você mais se sente você mesma?",
"Você é mais do tipo espontânea ou prefere planejar tudo com antecedência?",
"Qual foi a maior lição que você aprendeu até agora?",
"Qual seria o impacto de um bom conselho para você em um momento decisivo?",
"Qual é o momento perfeito para se sentir realmente feliz?",
"Você já teve um ‘momento de brilho’, onde sentiu que tudo fez sentido?",
"Qual é a sua forma favorita de se desconectar do mundo?",
"Você acha que o universo tem uma maneira de nos enviar sinais?",
"Qual é a coisa mais fofa que você já viu em um animal de estimação?",
"Qual seria a trilha sonora da sua vida nos últimos tempos?",
"Se você pudesse viver um dia de um filme ou livro, qual escolheria?",
"O que mais te motiva a seguir em frente quando está difícil?",
"Qual foi a última experiência de viagem que te transformou de alguma forma?",
"Qual seria o seu maior medo se você tivesse a chance de realizá-lo?",
"Você é mais do tipo que adora planejar ou ama se jogar na espontaneidade?",
"Qual foi a coisa mais legal que você aprendeu este ano?",
"Qual foi o momento mais impactante da sua vida até agora?",
"Você já teve um encontro totalmente inusitado? Como foi?",
"Qual é a maior qualidade que você procura em uma amizade?",
"Qual é a parte mais legal de ser você mesma?",
"Se você fosse criar uma viagem dos sonhos, como seria?",
"Qual é a sua definição de liberdade?",
"Você é do time de fazer planos ou de deixar as coisas acontecerem?",
"Se tivesse que escolher entre um dia perfeito de sol ou um dia de chuva, qual seria?",
"Você tem algum talento oculto ou algo que pouca gente conhece sobre você?",
"O que é algo que sempre te surpreende sobre as pessoas?",
"Você tem alguma superstição ou ritual pessoal para coisas importantes?",
"Qual foi o momento mais engraçado que você já viveu com os amigos?",
"Se tivesse que viver em uma cidade por um ano, qual escolheria?",
"Você já fez algo impulsivo que deu muito certo? O que foi?",
"Qual é a coisa mais divertida de se fazer sozinho, que você adora?",
"Qual foi o seu maior 'perrengue', mas que virou uma ótima história?",
"O que você mais curte fazer quando tem um tempo livre e sem pressa?",
"Se você pudesse passar o dia com qualquer pessoa do mundo, quem escolheria?",
"Qual é o tipo de viagem que você mais sonha em fazer?",
"Você já se surpreendeu com alguém que não imaginava? Como foi?",
"Qual é o lugar mais inusitado onde você já encontrou um pouco de paz?",
"O que te inspira no seu dia a dia?",
"Qual seria o projeto dos seus sonhos, se tivesse todo o tempo e dinheiro para fazer?",
"Se pudesse mudar de vida por um dia, qual seria a vida que você escolheria?",
"Qual é o seu conceito de felicidade?",
"Qual foi o melhor conselho de amor que já recebeu?",
"Qual é a parte mais divertida de estar com os amigos?",
"Qual é a sua maneira favorita de começar um dia?",
"Você é mais de aventuras ou de momentos tranquilos?",
"Se tivesse que escolher uma habilidade, qual seria?",
"Qual foi a maior descoberta que fez sobre si mesma nos últimos tempos?",
"Qual é a melhor maneira de se reconectar com as pessoas?",
"O que mais te excita sobre o futuro?",
"Qual é a sua maior ambição para os próximos anos?",
"Você tem algum ícone que te inspira na vida?",
"Qual é o tipo de experiência que mais te deixa feliz?",
"Você já teve alguma viagem que mudou sua perspectiva sobre algo?",
"Qual foi o maior desafio pessoal que você já superou?",
"Qual seria o presente perfeito para você agora?",
"Qual a parte mais legal de crescer e aprender mais sobre a vida?",
"Se pudesse voltar no tempo e dar um conselho para o seu eu do passado, o que diria?",
"Qual foi a maior surpresa boa que você já recebeu?",
"Qual foi a decisão mais importante que tomou até agora?",
"O que você mais espera alcançar nos próximos meses?",
"Qual seria a melhor maneira de comemorar um sonho ou objetivo realizado?"
        ],
        engracado: [
"Você já assistiu aquela serie(filme ou documentario sei lá) sobre [tema interessante]?",
"Eu estava pensando aqui, qual seria o seu superpoder ideal?",
"Você já teve alguma experiência maluca com viagens? Eu amo ouvir essas histórias?",
"Oi, você já experimentou [algo novo]? Eu estou bem curioso para saber como é.",
"O que você acha do [tema atual]? Achei que seria interessante discutir com alguém.",
"Eu preciso de uma recomendação de série, o que você está assistindo de bom?",
"Eu estava ouvindo [música] e lembrei de uma conversa que tivemos, tem alguma música que te faz lembrar de algo?",
"Se você fosse escolher um lugar para viajar agora, onde seria?",
"Sabe aquele momento em que você vê algo e fica pensando o que faria? Qual foi o último que aconteceu com você?",
"Tenho uma dúvida: qual é a melhor coisa para se fazer num final de semana chuvoso?",
"Acho que todo mundo tem uma história engraçada de infância, qual é a sua?",
"Estou tentando aprender [algo novo], você tem alguma dica para iniciantes?",
"Você acredita que alguma vez nos encontraremos em uma situação bem inesperada? Tipo, em uma viagem ou festa?",
"Se você pudesse morar em qualquer lugar do mundo por um mês, onde seria?",
"Eu estava lendo sobre [assunto curioso], o que você acha disso?",
"Se você fosse fazer algo fora da sua zona de conforto hoje, o que seria?",
"Eu estava pensando aqui, qual é a coisa mais aleatória que você já aprendeu na vida?",
"Se você fosse participar de um jogo de perguntas e respostas, qual pergunta te deixaria mais pensativa?",
"Sabe aquele meme que está bombando? Eu vi um e pensei, ‘isso é muito a cara de fulano’. E você, qual meme não te deixa de jeito nenhum?",
"Se você tivesse que escolher uma habilidade, o que escolheria instantaneamente aprender?",
"Quais são seus hobbies favoritos que a maioria das pessoas nem imagina que você gosta?",
"Eu estava pensando, qual é o maior clichê sobre [assunto] que você acha que é verdade?",
"Fico curioso, você tem alguma superstição ou algo que sempre faz antes de um grande evento?",
"O que você acha de [tendência atual]? Eu fico meio dividido às vezes.",
"Se você tivesse que se mudar para uma cidade nova amanhã, qual escolheria e por quê?",
"Você tem alguma mania estranha que as pessoas normalmente não acreditam quando você conta?",
"Qual é o melhor filme para assistir quando você quer apenas relaxar e se divertir?",
"Eu sempre tento encontrar um livro bom para ler, tem algum que você recomendaria?",
"Você já teve alguma experiência em um lugar completamente diferente do que você esperava?",
"Me conta uma coisa aleatória que você acha que todo mundo deveria saber!",
"Tem algo que você fez recentemente que te fez pensar ‘isso foi muito fora da caixa’?",
"Eu vi algo hoje e me lembrei de uma conversa nossa, você tem isso também?",
"Se você tivesse que escolher uma só para fazer no fim de semana: sair para uma festa ou ficar em casa assistindo algo que você ama?",
"Eu sempre fico pensando: qual é o segredo das pessoas que nunca param de rir?",
"Se você tivesse que fazer uma escolha difícil agora, o que escolheria: uma experiência de viagem ou uma experiência gastronômica incrível?",
"Qual foi o último evento ou coisa que te deixou realmente empolgado(a)?",
"Eu estou pensando em assistir uma série, tem alguma que você recomendaria?",
"O que você acha mais divertido: atividades ao ar livre ou explorar algo novo na cidade?",
"Você tem algum lugar favorito na cidade para desestressar e se sentir em paz?",
"Você tem alguma atividade que faz quando precisa de uma pausa da rotina?",
"Eu estava lendo sobre isso ontem e fiquei curioso, você já tentou [atividade curiosa]?",
"Tem algum lugar inusitado que você acha que todo mundo deveria visitar pelo menos uma vez na vida?",
"Se você tivesse que escolher entre ser uma pessoa super criativa ou super lógica, o que escolheria?",
"Eu amo quando encontro algo inesperado para fazer, tem alguma coisa que você fez recentemente que te pegou de surpresa?",
"Se você tivesse uma tarde livre para fazer qualquer coisa, como seria a sua escolha?",
"Qual seria a coisa mais louca que você faria se tivesse uma semana inteira de férias sem compromisso?",
"Qual seria a sua receita de conforto para um dia cansativo?",
"Eu adoro ouvir boas histórias, você tem alguma experiência de viagem que vale a pena compartilhar?",
"Qual é o melhor jeito de passar o tempo quando você está sem nada planejado para o dia?",
"Se tivesse que escolher entre ser uma pessoa super criativa ou super lógica, o que escolheria?",
"Qual foi a última coisa que você aprendeu e achou realmente útil?",
"Você tem algum lugar que considera como seu refúgio, onde sempre vai quando precisa de um tempo sozinho?",
"Qual foi a última coisa que te fez rir até não poder mais?",
"Se você tivesse que escolher um livro ou filme para maratonar, qual seria?",
"Qual seria o cenário perfeito para um dia relaxante?",
"Você tem alguma lembrança que te faz sorrir toda vez que pensa nela?",
"Se você tivesse que criar um feriado, o que ele comemoraria?",
"Tem algo simples, mas que te deixa realmente feliz no seu dia a dia?",
"Qual foi a última coisa que você fez por impulso e se arrependeu ou não?",
"Se você tivesse que escolher entre ser uma pessoa super criativa ou super lógica, o que escolheria?",
"Qual foi a última coisa que te surpreendeu de forma positiva?",
"Se você pudesse morar em qualquer lugar do mundo por um mês, onde seria?",
"Você tem alguma superstição que sempre segue, ou acha engraçado quando alguém acredita em uma?",
"Você tem algum conselho sobre o que fazer em um dia de tédio absoluto?",
"Se tivesse que escolher uma coisa para aprender imediatamente, o que escolheria?",
"Qual foi o último momento que você viveu que te deixou realmente feliz?",
"Eu adoro saber sobre coisas novas, tem algo que você tem aprendido ultimamente?",
"Qual foi a coisa mais inusitada que você aprendeu recentemente?",
"Você tem alguma coisa que quer muito fazer, mas ainda não teve a chance?",
"Qual foi a última experiência que te deixou realmente empolgado(a)?",
"Tem algo que você descobriu recentemente sobre si mesma que te surpreendeu?",
"Você já teve alguma experiência que te fez mudar completamente de ideia sobre algo?",
"Eu sou super curioso, qual foi a última coisa que te surpreendeu?",
"Qual seria a melhor forma de passar o tempo agora?",
"Você tem algum hábito estranho que todo mundo acha engraçado?",
"Você já fez algo recentemente só porque estava com vontade, sem pensar nas consequências?",
"Tem algo que você sempre quis aprender mas nunca conseguiu? Por que não?",
"Qual foi a última vez que você fez algo só para se divertir e sem pensar muito?",
"Se você pudesse trocar de vida com qualquer pessoa por um dia, quem seria?",
"O que você acha que todo mundo deveria fazer pelo menos uma vez na vida?",
"Qual seria a sua resposta para 'qual é o segredo da felicidade'?",
"Qual foi a última coisa que você fez que te fez se sentir realmente bem?",
"Você tem algum tipo de desafio ou meta pessoal que está perseguindo?",
"Qual foi o último conselho que você recebeu e realmente seguiu?",
"Qual foi o momento mais aleatório da sua vida até agora?",
"Eu adoro saber sobre as coisas que você curte, tem algo que você está realmente apaixonada agora?",
"Qual foi a coisa mais interessante que você aprendeu recentemente?",
"Se você tivesse que se mudar para outra cidade amanhã, qual escolheria?",
"Qual foi a última coisa que você fez e realmente se arrependeu ou não?",
"Você tem algum lugar que considera como seu refúgio, onde sempre vai quando precisa de um tempo sozinho?",
"Qual seria o cenário perfeito para um dia relaxante?",
"Qual foi a última coisa que você fez por impulso e se arrependeu ou não?",
"Se você tivesse que escolher uma coisa para aprender imediatamente, o que escolheria?",
"Qual é o melhor filme para assistir quando você quer apenas relaxar e se divertir?",
"Você já teve alguma experiência que te fez mudar completamente de ideia sobre algo?",
"Eu estava pensando sobre [tema] outro dia e me veio essa dúvida, o que você acha?",
"Se você fosse escolher um lugar para viajar agora, onde seria?",
"Você já teve alguma experiência que te deixou realmente empolgado(a)?",
"Qual foi a última coisa que você aprendeu e achou realmente útil?",
"Tem alguma atividade que você faz sozinha e que te faz sentir super bem?",
        ],
        flertes: [
            "Eu juro que vou tentar não parecer desesperado, mas você sempre me faz sorrir sem nem perceber, haha,",
"Será que a gente poderia trocar de lugar por um dia? Eu sempre quis ver o mundo pelos seus olhos, já que é tão interessante, hehe,",
"Eu estava pensando... você tem aquele sorriso que faz tudo parecer melhor. Tem como você me deixar ver mais dele?,",
"Fica a dúvida, você tem esse charme natural ou é só para mim?,",
"Estou tentando me concentrar em outra coisa, mas você não sai da minha cabeça. Você tem algum truque para isso?,",
"Você tem uma habilidade especial de fazer o tempo passar voando... ou será que é só quando estamos conversando?,",
"Tem algo que você não pode fazer em público? Porque me parece que só de estar perto de você já me faz perder a linha, haha,",
"Eu estava pensando aqui, que tipo de loucura você faria se fosse para sair agora? Aposto que seria algo bem espontâneo... quem sabe comigo, hehe,",
"Aposto que você sabe como causar uma boa impressão. O que você acha de tentar deixar o meu dia melhor?,",
"Você tem um talento secreto para deixar as conversas mais interessantes ou é só um efeito colateral de ser tão incrível?,",
"Eu sempre tento não ser óbvio, mas você é do tipo que faz qualquer um esquecer o que estava fazendo, não é?,",
"Eu estava só imaginando... já pensou como seria interessante a gente trocar umas ideias de madrugada?,",
"Sabe o que eu reparei? Toda vez que você fala, eu fico prestando mais atenção do que no que estava fazendo antes, hehe,",
"Você tem o poder de transformar um dia normal em algo muito mais interessante só com sua presença, sabia?,",
"Eu tava pensando... se a gente se encontrasse num lugar inesperado, o que seria mais divertido: tentar sair ou aproveitar a situação?,",
"Você é a pessoa que eu queria por perto quando algo incrível acontece. Será que posso contar contigo para o próximo momento?,",
"Agora me conta, é só eu ou todo mundo fica mais animado quando você começa a falar?,",
"Você tem o dom de fazer tudo parecer mais interessante. Como você consegue fazer isso sem nem tentar?,",
"Eu juro que tento focar na conversa, mas fico distraído toda vez que você sorri, haha,",
"Acho que o mais difícil é escolher qual é a melhor coisa sobre você: seu jeito ou o fato de que você não precisa nem tentar para ser perfeita?,",
"Eu sempre quis saber... o que te faz sorrir de verdade? Porque o seu sorriso é quase um truque de mágica.,",
"Qual é o segredo para ser tão fácil de gostar? Eu realmente queria saber, haha,",
"Não sei se você sabe, mas acho que você tem esse poder de deixar o ambiente mais animado só de estar perto. Como você faz isso?,",
"Eu fico pensando, se um dia a gente se encontrasse por aí, eu teria coragem de te falar tudo o que penso ou ficaria só no olhar?,",
"Parece que sempre que você aparece, o meu dia fica mais interessante. Será que é só comigo?,",
"Eu estava tentando me concentrar em outra coisa, mas o seu nome apareceu na minha cabeça... agora não consigo parar de pensar nisso, hehe,",
"Sabia que você tem uma maneira toda especial de deixar qualquer dia melhor? Eu adoraria saber como você faz isso.,",
"Sempre fico curioso... como você consegue ser tão incrível e não fazer esforço nenhum?,",
"Eu estava só pensando aqui... será que você é a pessoa mais interessante da cidade ou estou começando a achar isso só porque você está aqui?,",
"Eu tenho uma aposta... você consegue fazer qualquer pessoa sorrir com um simples gesto, acertei?,",
"Já percebeu que sua voz tem o poder de fazer qualquer conversa ficar mil vezes melhor?,",
"Você tem esse poder de deixar tudo mais leve. Eu aposto que até o ar ao seu redor fica mais gostoso, hehe,",
"Eu tenho uma teoria... você tem algum tipo de superpoder? Porque sempre que você está por perto, tudo melhora.,",
"Não quero soar clichê, mas você é daquele tipo que faz qualquer lugar parecer mais interessante só com sua presença, sabia?,",
"Sabe o que seria perfeito? A gente sair juntos e ver se a realidade consegue ser tão divertida quanto a ideia, hehe,",
"Eu estava pensando aqui, você é do tipo que transforma qualquer lugar em um evento especial, ou isso é só comigo?,",
"Eu fico tentando entender, o que é mais interessante em você: sua conversa ou sua energia? Acho que as duas coisas são imbatíveis, hehe,",
"Não sei se é só comigo, mas parece que sempre que você fala, tudo ao redor fica mais interessante. Já percebeu isso?,",
"Eu sempre fico mais interessado no que você tem a dizer. Você tem uma fórmula mágica para deixar tudo mais empolgante?,",
"Eu não sei o que você tem, mas sempre que você fala, é como se eu tivesse que ouvir. Acho que vou começar a chamar isso de 'efeito você', hehe,",
"Eu estava só pensando aqui, se a gente se esbarrasse na rua, o que você acha que seria mais divertido? Nos reconhecer ou tentar uma conversa, haha?",
"Não sei se você percebeu, mas cada vez que você me manda uma mensagem, meu dia melhora 100%. Você tem ideia do impacto que causa?,",
"Eu sempre quis saber, como alguém pode ser tão descomplicado e ao mesmo tempo tão encantador?,",
"Você sempre tem uma opinião tão interessante... será que se eu te perguntasse sobre [assunto], você me deixaria mais curioso ainda?,",
"Eu estava pensando em como seria se a gente se encontrasse por aí. Você acha que seríamos dois estranhos ou já estaria rolando uma conversa natural?,",
"Eu não sei como você faz isso, mas sempre que fala, tudo ganha um novo significado. Tem algum segredo para isso?,",
"Sabe aquela sensação boa quando algo inesperado acontece? Acho que a gente poderia fazer isso junto, hehe,",
"Eu fiquei pensando aqui, a nossa conversa tem aquele toque especial, você sempre me deixa querendo saber mais. Como você faz isso?,",
"Eu sempre fico curioso: qual é a primeira coisa que vem na sua cabeça quando você me vê?,",
"Já reparou como cada mensagem sua tem um efeito em mim? Se eu fosse mais corajoso, diria que é como um feitiço",
"Você já percebeu que sua presença faz qualquer lugar parecer mais interessante? Aposto que você tem esse poder, hehe",
"Eu não sei o que você tem, mas quando você me olha, parece que o resto do mundo desaparece. Isso é normal?",
"Eu estava pensando aqui, se eu tivesse que passar um dia inteiro com alguém, acho que seria com você. Só para ver se a diversão seria garantida, hehe",
"Parece que a sua energia é contagiante, sempre que você aparece, o dia fica melhor. Como você faz isso?",
"Eu sempre tento ser legal, mas quando você fala, fico sem palavras. Como você faz isso?",
"Você sabe que tem esse efeito de deixar tudo mais leve, né? Como você consegue ser tão natural assim?",
"Sempre que você entra na conversa, tudo ganha uma nova perspectiva. Acho que você é mais interessante do que imagina, hehe",
"Se eu te chamasse para uma aventura hoje, acha que toparia ou ficaria curiosa demais para resistir?",
"Já reparou como tudo parece mais fácil quando você está por perto? Aposto que é só por causa da sua companhia, hehe",
"Eu estava aqui tentando focar no meu trabalho, mas seu nome apareceu na minha mente de repente. Acontece com você também?",
"Eu acho que se você me ensinasse a ser mais espontâneo, a vida ficaria bem mais divertida. Que tal começarmos agora?",
"Você tem esse jeito de transformar o simples em algo interessante. Já tentou usar isso para conquistar o mundo?",
"Eu não sei o que você faz, mas sempre que estou perto de você, fico querendo aproveitar mais a vida. Será que você me contaria o segredo?",
"Parece que você tem um botão de 'boa energia' dentro de você. Como você faz isso sem nem tentar?",
"A cada conversa com você, fico pensando que deveria aprender mais com você, porque você tem essa leveza incrível. Que tal me ensinar?",
"Se você fosse um personagem de filme, acho que seria o tipo que todo mundo quer conhecer. Como é ser tão interessante assim?",
"Eu estava pensando aqui, qual seria a melhor forma de fazer você rir hoje? Talvez eu consiga dar um show de piadas ou te surpreender, haha",
"Não sei se você tem ideia, mas sempre que você sorri, o meu dia melhora 10 vezes. O que você tem de tão encantador?   MINHA FAVORITA",
"Eu nunca imaginei que seria tão fácil me perder na conversa com alguém. Mas aí você apareceu e tudo ficou muito mais interessante.",
"Se a gente fosse se conhecer de novo, qual seria a primeira coisa que você me diria? Eu acho que você me surpreenderia, hehe",
"Sempre que você manda uma mensagem, fico na expectativa. Como você faz para me deixar tão curioso assim?",
"Você sabe, sempre que eu tento pensar em algo mais interessante, acabo lembrando de você. Acho que é impossível não, hehe",
"Acho que a gente deveria fazer algo que ninguém mais faz: conversar por horas e descobrir o que mais temos em comum, haha",
"Você já reparou como toda conversa com você é como uma nova aventura? Aposto que é impossível não se divertir com você por perto, hehe",
"Eu sou do tipo que gosta de surpresas, mas as suas já são incríveis por si só. Como você consegue ser tão única?",
"Eu estava pensando, você deve ser a pessoa mais interessante da sala toda. Todo mundo sempre fica prestando atenção quando você fala, hehe",
"Será que a gente conseguiria se encontrar por acaso e a conversa fluir do jeito mais divertido possível? Eu aposto que sim!",
"Eu estava aqui imaginando como seria se a gente fizesse algo totalmente inesperado. O que você acha de se arriscar um pouco?",
"Parece que você tem uma habilidade de fazer qualquer dia normal parecer épico. Como você faz isso?",
"Já pensou em fazer algo de que nunca se arrependeria? Eu acho que seria algo com uma companhia como a minha, hehe",
"Você tem uma dessas vibrações boas que me fazem querer estar perto mais vezes. É algo que você carrega por aí, ou é só pra mim?",
"Eu não sei se é só eu, mas sempre que você aparece, fico com um sorriso bobo na cara. Isso acontece com mais alguém ou só comigo?",
"Eu estava pensando aqui, você tem algo de tão encantador que fica difícil não querer te conhecer melhor. Que tal me contar mais sobre você?",
"Eu não sei o que você tem, mas sempre que você fala, fico mais interessado. Acho que você deve ter um segredo incrível.",
"Você tem um desses jeitos únicos de fazer qualquer conversa ser interessante. Como você consegue fazer isso com tanta naturalidade?",
"Eu acho que você tem um talento secreto para fazer qualquer um se sentir especial. Como faz isso sem nem tentar?",
"Eu estava aqui pensando... será que um dia poderíamos nos encontrar por aí e deixar a conversa fluir sem parar?",
"Eu sempre fico mais animado quando você fala. Qual é o segredo para conseguir essa magia?",
"Será que a gente já se cruzou por aí sem perceber? Porque toda vez que você fala, parece que nossa conversa é tipo um reencontro.",
"Eu estava tentando me concentrar em outra coisa, mas você sempre acaba roubando minha atenção. Acho que você tem esse poder!",
"Será que, se a gente se encontrasse hoje, teria algum tipo de conexão instantânea? Porque parece que isso já acontece virtualmente, hehe",
"Você sempre tem uma maneira de me fazer sorrir. Já pensou em usar esse poder de forma profissional?",
"Você sabe que tem esse talento para fazer tudo ficar mais interessante? Se eu fosse você, usaria isso ao meu favor o tempo todo, hehe",
"Sempre que você fala, me sinto como se estivesse ouvindo uma boa história. Acho que você poderia me contar todas as suas aventuras, haha",
"Eu não sei como você faz, mas toda vez que você responde, o dia fica mais empolgante. Que tal me contar mais sobre o seu mundo?",
"Você já percebeu que sempre que você aparece, minha atenção vai toda para você? Eu acho que é impossível não ser assim.",
"Eu não sei como você consegue, mas sempre que está por perto, eu fico mais curioso para saber mais sobre você. Está tudo certo ou você está me conquistando sem querer?",
"Sabe o que seria ótimo? Eu e você, uma conversa tranquila e nenhuma expectativa. Só para ver o que acontece. Que tal?",
"Eu estava pensando aqui, como seria ótimo se a gente fizesse algo completamente diferente da rotina. Você toparia?",
"Eu realmente não sei o que você tem, mas todas as vezes que falamos, a conversa fica mais divertida. Acho que você tem o poder de tornar qualquer dia melhor.",
        ]
    };

   
    const titulos = {
        romantico: "Conselhos para Clima Romântico como o ZANT",
        engracado: "Conselhos para Quebrar o Gelo como o ZANT",
        flertes: "Conselhos de Flertes como o ZANT"
    };

    
    titulo.textContent = titulos[tipo] || "Conselhos";
    tbody.innerHTML = ""; 

    
    conselhos[tipo].forEach(conselho => {
        const row = document.createElement('tr');
        const cell = document.createElement('td');
        cell.textContent = conselho;
        row.appendChild(cell);
        tbody.appendChild(row);
    });

    container.classList.remove('oculto');
}
